services:
  postgres-dev:
    image: postgres:16
    container_name: taskflow-dev
    env_file:
      - .dev.env
    ports:
      - "5433:5432"
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    profiles:
      - dev
    networks:
      - backend_default
    restart: always

  postgres-prod:
    image: postgres:16
    container_name: taskflow-prod
    env_file:
      - .prod.env
    ports:
      - "5432:5432"
    volumes:
      - postgres-prod-data:/var/lib/postgresql/data
    profiles:
      - prod
    networks:
      - backend_default
    restart: always

  backend-dev:
    image: dantechhjkim/backend-dev:latest
    container_name: backend-dev
    env_file:
      - .dev.env
    volumes: 
      - ./sftpuser-dev_id_rsa:/app/sftpuser-dev_id_rsa:ro
      - ./google-calendar.json:/app/google-calendar.json:ro
    depends_on:
      - postgres-dev
    ports:
      - "3000:3000"
    profiles:
      - dev
    networks:
      - backend_default
    restart: unless-stopped

  backend-prod:
    image: dantechhjkim/backend-prod:latest
    container_name: backend-prod
    env_file:
      - .prod.env
    volumes: 
      - ./sftpuser_id_rsa:/app/sftpuser_id_rsa:ro
      - ./google-calendar.json:/app/google-calendar.json:ro
    depends_on:
      - postgres-prod
    expose:
      - "3000"
    profiles:
      - prod
    networks:
      - backend_default
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: taskflow-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    profiles:
      - dev
      - prod
    networks:
      - backend_default
    restart: always

  doc-converter:
    image: gotenberg/gotenberg:latest
    container_name: doc-converter
    volumes:
      - ./fonts:/usr/share/fonts:ro
    ports:
      - "3001:3001"
    networks:
      - backend_default
    profiles:
      - dev
      - prod
    restart: always

volumes: 
  postgres-dev-data:
  postgres-prod-data:
  redis-data:

networks:
  backend_default:
    external: true